m3-w8d1-controllers-part1-exercises/Exercises.Web/Models/ColorizerModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Exercises.Web.Models
{
    public class ColorizerModel
    {
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public string MiscellaneousColor { get; set; }

        [Display(Name = "Red")]
        public bool IsRed { get; set; }
        public bool IsBlue { get; set; }
        public bool IsGreen { get; set; }
    }
}

m3-w8d1-controllers-part1-exercises/Exercises.Web/Controllers/ColorizerController.cs
using Exercises.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Exercises.Web.Controllers
{
    public class ColorizerController : Controller
    {
        // GET: Colorizer
        public ActionResult ColorizedForm()
        {
            ColorizerModel model = new ColorizerModel();
            return View("ColorizedForm", model); //pass the model into the view
        }

        public ActionResult ColorizedFormResult(ColorizerModel input)
        {
            ColorizerModel model = input;
            return View("ColorizedFormResult", model);
        }
    }
}

m3-w8d1-controllers-part1-exercises/Exercises.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Exercises.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

m3-w8d1-controllers-part1-exercises/Exercises.Web/Views/Colorizer/ColorizedForm.cshtml
@using Exercises.Web.Models;
@model ColorizerModel

@{
    ViewBag.Title = "ColorizedForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Form</h2>

<form action="@Url.Action("ColorizedFormResult", "Colorizer")" method="get">

    <div>
        @Html.LabelFor(m => m.FirstName)
        @Html.TextBoxFor(m => m.FirstName)
    </div>
    <div>
        @Html.LabelFor(m => m.LastName)
        @Html.TextBoxFor(m => m.LastName)
    </div>

    <div>
        @Html.CheckBoxFor(m => m.IsRed) @Html.LabelFor(m => m.IsRed)
        @Html.CheckBoxFor(m => m.IsBlue) @Html.LabelFor(m => m.IsBlue)
        @Html.CheckBoxFor(m => m.IsGreen) @Html.LabelFor(m => m.IsGreen)
    </div>

    <div>
        <select name="MiscellaneousColor">
            <option value="#FF69B4">Hot Pink</option>
            <option value="#FFD700">Gold</option>
            <option value="#593001">Marty</option>
        </select>
    </div>

    <button>Submit!</button>
</form>

m3-w8d1-controllers-part1-exercises/Exercises.Web/Views/Colorizer/ColorizedFormResult.cshtml
@using Exercises.Web.Models;
@model ColorizerModel



@{
    ViewBag.Title = "ColorizedFormResult";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Result</h2>

<p>First Name: @Model.FirstName</p>
<p>Last Name: @Model.LastName</p>

@if (Model.IsRed)
{
    <p style="color: red;">Red: @Model.FirstName @Model.LastName</p>
}

@if (Model.IsBlue)
{
    <p style="color: blue;">Blue: @Model.FirstName @Model.LastName</p>
}

@if (Model.IsGreen)
{
    <p style="color: green;">Green: @Model.FirstName @Model.LastName</p>
}

@if (!String.IsNullOrEmpty(Model.MiscellaneousColor))
{
    <p style="color: @Model.MiscellaneousColor">@Model.FirstName @Model.LastName</p>
}

m3-w8d1-controllers-part1-exercises/Exercises.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

m3-w8d1-controllers-part1-exercises/Exercises.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>