m5-critter/Critter.Web/Controllers/CritterController.cs
using Critter.Web.DataAccess;
using Critter.Web.Models.Data;
using Critter.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Critter.Web.Controllers
{
    public class CritterController : Controller
    {
        private const string UsernameKey = "Critter_UserName";
        private readonly IUserDAL userDal;

        public CritterController(IUserDAL userDal)
        {
            this.userDal = userDal;
        }


        /// <summary>
        /// Gets the value from the Session
        /// </summary>
        public string CurrentUser
        {
            get
            {
                string username = string.Empty;

                //Check to see if user cookie exists, if not create it
                if (Session[UsernameKey] != null)
                {
                    username = (string)Session[UsernameKey];
                }

                return username;
            }
        }

        /// <summary>
        /// Returns bool if user has authenticated in
        /// </summary>        
        public bool IsAuthenticated
        {
            get
            {
                return Session[UsernameKey] != null;
            }
        }

        /// <summary>
        /// "Logs" the current user in
        /// </summary>
        public void LogUserIn(string username)
        {
            Session[UsernameKey] = username;            
        }

        /// <summary>
        /// "Logs out" a user by removing the cookie.
        /// </summary>
        public void LogUserOut()
        {
            Session.Abandon();
            //Response.Cookies.Add(new HttpCookie("ASP.NET_SessionId", ""));
        }


        [ChildActionOnly]
        public ActionResult GetAuthenticatedUser()
        {
            User model = null;

            if (IsAuthenticated)
            {
                model = userDal.GetUser(CurrentUser);
            }

            return View("_AuthenticationBar", model);
        }


    }
}

m5-critter/Critter.Web/Views/Shared/_AuthenticationBar.cshtml
@using Critter.Web.Extensions;
@model Critter.Web.Models.Data.User

@if (Model == null) //unauthenticated
{   
    <ul class="nav navbar-nav navbar-right">
        <li class="@Html.IsSelected("Users", "NewUser", "active")">@Html.ActionLink("Sign Up", "NewUser", "Users")</li>
        <li class="@Html.IsSelected("Users", "Login", "active")">@Html.ActionLink("Log In", "Login", "Users")</li>
    </ul>
}
else //authenticated
{
    <ul class="nav navbar-nav">
        <li class="@Html.IsSelected("Home", "Index", "active")">@Html.ActionLink("Home", "Index", "Home")</li>
        <li class="@Html.IsSelected("Messages", "Dashboard", "active")">@Html.ActionLink("Private Messages", "Dashboard", "Messages", new { username = Model.Username }, null)</li>
        <li class="@Html.IsSelected("Messages", "NewMessage", "active")">@Html.ActionLink("New Message", "NewMessage", "Messages", new { username = Model.Username }, null)</li>
        <li class="@Html.IsSelected("Messages", "SentMessages", "active")">@Html.ActionLink("Sent Messages", "SentMessages", "Messages", new { username = Model.Username }, null)</li>
        <li class="@Html.IsSelected("Messages", "ChangePassword", "active")">@Html.ActionLink("Change Password", "ChangePassword", "Users", new { username = Model.Username }, null)</li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
        <li><a href="@Url.Action("Dashboard", "Messages", new { username = Model.Username })">Hello @Model.Username</a></li>
        <li>@Html.ActionLink("Log Out", "Logout", "Users")</li>
    </ul>

        
}

m5-critter/Critter.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />    
    <title>Critter</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link rel="shortcut icon" href="~/Content/img/favicon.ico" />
    <link rel="stylesheet" href="~/Content/stylesheet.css" />
    <script src="~/Scripts/jquery-2.2.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="http://cdn.jsdelivr.net/jquery.validation/1.15.0/additional-methods.js "></script>    
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery.timeago.js"></script>
    <script src="~/Scripts/jquery.autocomplete.js"></script>
    <script src="~/Scripts/critterApiService.js"></script>
    <script src="~/Scripts/messageThreadRefresh.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("time.timeago").timeago();
        })
    </script>
</head>
<body>
    <header>
        <a href="@Url.Action("Index", "Home")"><img src="~/Content/img/logo.png" class="img-responsive" /></a>
    </header>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#critterNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>                
            </div>
            <div class="collapse navbar-collapse" id="critterNavBar">
                @Html.Action("GetAuthenticatedUser", "Critter")
            </div>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>

    <footer>
        Copyright @DateTime.Now.Year Critter Inc.
    </footer>

</body>
</html>